# general settings
name: BasicVSR_saup_Vimeo90K_BIx2
model_type: ASVideoRecurrentModel
scale: !!python/tuple [2, 2]
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: ASVimeo90KRecurrentDataset
    dataroot_gt: datasets/vimeo90k/vimeo_septuplet/sequences
    dataroot_lq: datasets/vimeo90k/BIx4
    meta_info_file: lbasicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    io_backend:
      type: disk

    num_frame: -1
    # arbitrary scale dataset --------------------------
    lq_size: 64                         # gt_size = lq_size * current_scale
    downsample_mode: torch              # [torch, core, numpy]
    init_int_scale: false               # scale x2, x3, x4 for 1 epoch
    single_scale_ft: true               # only a scale
    CL_train_set: ~                     # Continuous learning training strategy
    # --------------------------------------------------
    gt_size: 256                        # not needed
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 200
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: Vid4
    type: ASVideoRecurrentTestDataset
    dataroot_gt: datasets/Vid4/GT
    dataroot_lq: datasets/Vid4/BIx4

    cache_data: True
    io_backend:
      type: disk

    num_frame: -1  # not needed
    # arbitrary scale dataset --------------------------
    use_arbitrary_scale_downsampling: true
    downsampling_scale: !!python/tuple [4, 4]
    downsampling_mode: torch
    # --------------------------------------------------

# network structures
network_g:
  type: BasicVSR
  num_feat: 64
  num_block: 30
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth
  # scale: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
