# general settings
name: PFNL_REDS_BIx4
model_type: VideoBaseModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSDataset
    # dataroot_gt: datasets/REDS/train_sharp
    # dataroot_lq: datasets/REDS/train_sharp_bicubic/X4
    dataroot_gt: datasets/REDS/train_sharp_with_val.lmdb
    dataroot_lq: datasets/REDS/train_sharp_bicubic_with_val.lmdb
    dataroot_flow: ~
    meta_info_file: lbasicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      # type: disk
      type: lmdb

    num_frame: 7
    gt_size: 128
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoTestDataset
    dataroot_gt: datasets/REDS/train_sharp
    dataroot_lq: datasets/REDS/train_sharp_bicubic/X4
    meta_info_file: lbasicsr/data/meta_info/meta_info_REDS4_test_GT.txt
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    io_backend:
      type: disk

    cache_data: false
    num_frame: 7
    padding: reflection_circle

# network structures
network_g:
  type: PFNL
  num_frames: 7
  n_filters: 64
  n_block: 20
  scale: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    # type: CosineAnnealingRestartLR
    # periods: [150000, 150000, 150000, 150000]
    # restart_weights: [1, 0.5, 0.5, 0.5]
    # eta_min: !!float 1e-7
    # --------------------------------
    type: MultiStepLR
    milestones: [120000]        # official MM522: [120000]
    gamma: 0.1

  total_iter: 150000            # official MM522: [120000]
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
