# general settings
name: RVRT_REDS_30frames_BIx3
model_type: VRTModel
scale: !!python/tuple [3, 3]
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: ASREDSRecurrentDataset
    dataroot_gt: datasets/REDS/train_sharp
    dataroot_lq: datasets/REDS/train_sharp_bicubic/X4
    meta_info_file: lbasicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    test_mode: False
    io_backend:
      type: disk

    num_frame: 30
    # arbitrary scale dataset --------------------------
    lq_size: 64
    downsample_mode: torch              # [torch, core, numpy]
    single_scale_ft: true               # only a x2 scale
    # --------------------------------------------------
    gt_size: 256                        # not needed
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8         # 6
    batch_size_per_gpu: 1         # for 2 A6000: 1, default: 8
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4_x3
    type: ASVideoRecurrentTestDataset
    dataroot_gt: datasets/REDS4/GT
    dataroot_lq: datasets/REDS4/sharp_bicubic

    cache_data: True
    io_backend:
      type: disk

    num_frame: -1  # not needed
    # arbitrary scale dataset --------------------------
    use_arbitrary_scale_downsampling: true
    downsampling_scale: !!python/tuple [3, 3]
    downsampling_mode: torch
    # --------------------------------------------------

# network structures
network_g:
  type: RVRT
  upscale: 3
  clip_size: 2
  img_size: [2, 64, 64]
  window_size: [2, 8, 8]
  num_blocks: [1, 2, 1]
  depths: [2, 2, 2]
  embed_dims: [144, 144, 144]
  num_heads: [6, 6, 6]
  inputconv_groups: [1, 1, 1, 1, 1, 1]
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth
  deformable_groups: 12
  attention_heads: 12
  attention_window: [3, 3]
  use_checkpoint_attn: true     # default: false
  use_checkpoint_ffn: true
  no_checkpoint_attn_blocks: []
  no_checkpoint_ffn_blocks: []
  cpu_cache_length: 100

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: experiments/RVRT_REDS_30frames_BIx3/training_states/230000.state

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up

  fix_iter: 30000
  flow_lr_mul: 0.25
  fix_keys: ['spynet']

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
    eps: !!float 1e-9

# validation settings
val:
  val_freq: !!float 1e4     # 5e3
  save_img: false

  num_frame_testing: 0
  num_frame_overlapping: 2
  size_patch_testing: 128

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4     # 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: false
use_static_graph: true
