# general settings
name: 103_EDVR_L_x2_SR_REDS_woTSA_600k_B4G8_valREDS4_wandb
model_type: EDVRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: ASREDSDataset
    # dataroot_gt: datasets/REDS/train_sharp
    dataroot_gt: datasets/REDS/train_sharp_with_val.lmdb
    # dataroot_lq: datasets/REDS/train_sharp_bicubic/X4
    dataroot_lq: datasets/REDS/train_sharp_bicubic_with_val.lmdb
    dataroot_flow: ~
    meta_info_file: lbasicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: lmdb

    num_frame: 5
    # ------ arbitrary-scale setting ---------------------------
    lq_size: 64
    downsample_mode: torch              # [torch, core, numpy]
    single_scale_ft: true               # only a scale
    # ----------------------------------------------------------
    gt_size: 256                        # if type: ASREDSDataset, not needed
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 200
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: REDS4_x2
    type: ASVideoTestDataset
    dataroot_gt: datasets/REDS/train_sharp
    dataroot_lq: datasets/REDS/train_sharp_bicubic/X4
    meta_info_file: lbasicsr/data/meta_info/meta_info_REDS4_test_GT.txt
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    io_backend:
      type: disk

    cache_data: false
    num_frame: 5
    padding: reflection_circle
    # arbitrary scale setting
    use_arbitrary_scale_downsampling: true
    downsampling_scale: !!python/tuple [2, 2]
    downsampling_mode: torch

# network structures
network_g:
#  ema_decay: 0.999
  type: EDVR_x2
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 128
  num_frame: 5
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 40
  center_frame_idx: ~
  hr_in: false
  with_predeblur: false
  with_tsa: false

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000, 150000, 150000, 150000]
    restart_weights: [1, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
