# general settings
name: liif-rdn-norm_c64b16_1xb16-1000k_div2k
model_type: LIIFModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: ASINRImageDataset
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub
    # (for lmdb)
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      # type: disk
      # (for lmdb)
      type: lmdb

    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    lr_patch_size: 48
    scale_range: [1, 4]
    sample_quantity: 2304
    reshape_gt: true
    
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 16
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: ASINRImageDataset
    dataroot_gt: datasets/Set5/GTmod12
    # dataroot_lq: datasets/Set5/LRbicx4
    io_backend:
      type: disk
    reshape_gt: false
    val_scale: !!python/tuple [4, 4]

  val_2:
    name: Set14
    type: ASINRImageDataset
    dataroot_gt: datasets/Set14/GTmod12
    # dataroot_lq: datasets/Set14/LRbicx4
    io_backend:
      type: disk
    reshape_gt: false
    val_scale: !!python/tuple [4, 4]
  
  val_3:
    name: B100
    type: ASINRImageDataset
    dataroot_gt: datasets/B100/GT
    io_backend:
      type: disk
    reshape_gt: false
    val_scale: !!python/tuple [4, 4]
  
  val_4:
    name: Urban100
    type: ASINRImageDataset
    dataroot_gt: datasets/Urban100/GT
    io_backend:
      type: disk
    reshape_gt: false
    val_scale: !!python/tuple [4, 4]


# network structures
network_g:
  type: LIIFRDN
  encoder:
    type: RDN
    num_in_ch: 3
    num_out_ch: 3
    num_feat: 64
    num_block: 16
    upscale: 4
    num_layer: 8
    channel_growth: 64
  imnet:
    type: MLPRefiner
    in_dim: 64
    out_dim: 3
    hidden_list: [256, 256, 256, 256]
  local_ensemble: true
  feat_unfold: true
  cell_decode: true
  eval_bsize: 30000

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: experiments/liif-rdn-norm_c64b16_1xb16-1000k_div2k/training_states/95000.state

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000, 400000, 600000, 800000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr_y: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim_y:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
