# general settings
name: OVSR_govsr_8+4_56_Vimeo90K_BIx4
model_type: OVSRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90KRecurrentDataset
#    V100
#    dataroot_gt: datasets/vimeo90k/vimoe_septuplet_origin/vimeo_septuplet/sequences
#    dataroot_lq: datasets/vimeo90k/vimeo_septuplet_matlabLRx4/sequences
#    3090
    dataroot_gt: datasets/vimeo90k/vimoe_septuplet_origin/vimeo_septuplet/sequences
    dataroot_lq: datasets/vimeo90k/vimeo_septuplet_matlabLRx4/sequences
    meta_info_file: lbasicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    io_backend:
      type: disk

    num_frame: -1
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: false

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: Vid4
    type: VideoRecurrentTestDataset
    dataroot_gt: datasets/Vid4/GT
    dataroot_lq: datasets/Vid4/BIx4
#    3090
#    dataroot_gt: /data2/lzk_data/workspace/LbasicSR/datasets/Vid4/GT
#    dataroot_lq: /data2/lzk_data/workspace/LbasicSR/datasets/Vid4/BIx4
#    V100
#    dataroot_gt: /data1/lzk_data/workspace/LbasicSR/datasets/Vid4/GT
#    dataroot_lq: /data1/lzk_data/workspace/LbasicSR/datasets/Vid4/BIx4

    cache_data: True
    io_backend:
      type: disk

    num_frame: -1  # not needed

# network structures
network_g:
  type: OVSR
  num_feat: 56
  num_pb: 8               # number of residual blocks in the precursor
  num_sb: 4               # number of residual blocks in the successor
  scale: 4                # sr scale
  num_frame: 7            # we adopt one frame from the past, present, and future respectively
  kind: 'global'          # local or global

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  alpha: 0.01             # hyper-parameter to adjust the weight of precursor in loss, 0.01 and 0.1 for global and local should be fine
  sub_frame: 1            # number of frames at the beginning and the end not used for computing the loss during training
#  ema_decay: 0.9
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [ 0.9, 0.99 ]

  scheduler:
    # =============================================
#    type: CosineAnnealingRestartLR
#    periods: [ 50000, 50000, 50000, 50000 ]
#    restart_weights: [ 1, 0.5, 0.5, 0.5 ]
#    eta_min: !!float 1e-7
    # =============================================
    type: MultiStepLR
#    milestones: [50000, 100000, 150000, 200000]
    milestones: [300000, 600000]
    gamma: 0.1
#    restarts: [150000, 150000, 150000, 150000]
#    restart_weights: [ 1, 0.1, 0.1, 0.1 ]
#  ==============================================
#    restart test
#    restarts: [16, 32]
#    restart_weights: [ 1, 0.1 ]
#  ==============================================
#    eta_min: !!float 1e-7

  total_iter: 600000    #600000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e3
  save_img: false

  metrics:
    psnr_y: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true
    ssim_y:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
